const locationCodeMap: Record<string, string> = {
    '서울': 'SEL',
    '부산': 'PUS',
    '대구': 'TAE',
    '도쿄': 'TYO',
    '오사카': 'OSA',
    '다낭': 'DAD',
    '런던': 'LON',
    '후쿠오카': 'FUK',
    '시드니': 'SYD',
    '교토': 'UKY',
    '삿포로': 'SPK',
    '오키나와': 'OKA',
    '방콕': 'BKK',
    '치앙마이': 'CNX',
    '하노이': 'HAN',
    '호이안': 'HOI',
    '냐짱': 'NHA',
    '세부': 'CEB',
    '로스엔젤레스': 'LAX',
    '토론토': 'YYZ',
    '뉴욕': 'NYC',
    '라스베이거스': 'LAS',
    '벤쿠버': 'YVR',
    '멜버른': 'MEL',
    '오클랜드': 'AKL',
    '골드코스트': 'OOL',
    '브리즈번': 'BNE',
    '뉴질랜드': 'NZL',
    '아시아': 'ASI',
    '동남아시아': 'SEA',
    '동아시아': 'EAS',
    '유럽': 'EUR',
    '미주': 'AMR',
    '오세아니아': 'OCN',
};

export const changeToThreeLetter = (location: string) => {
    return locationCodeMap[location] ?? location.slice(0, 3).toUpperCase();
};